### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by GreenReaper** [allentc/pgadmin3-lts#18]
The project readme claims that "Binaries for the application are presently produced on Windows & OSX to manage PostgreSQL 8.4 and above." but perhaps this is not the case for this fork?

(I was sorta hoping to get it running on Windows Vista 32-bit, since browsers stopped supporting Vista before the versions that pgadmin4 supports and I have a few old 32-bit machines on that, but I appreciate that might realistically be a pipe dream.)

**Comment by VVD** [comment]
What about release with sources in "official" tarball?

**Comment by rossnick** [comment]
@VVD Compiling for Linux isn't that hard. It's more on Windows and Mac that is far more difficult. A few years back, I tried to compile for Windows during the time Bigsql was managing this code, and never succeeded.

**Comment by VVD** [comment]
@rossnick, I said about tarball with sourses (yes, it's offtopic, sorry).

I'm a maintainer of several ports (packages) in FreeBSD and found that current version of pgadmin3 is abandoned, pgadmin4 is …very bad… and found this fork (and AbdulYadi's fork too). I want to create port with active fork (or replace existing) and need some "point" for distfiles.

**Comment by allentc** [comment]
> The project readme claims that "Binaries for the application are presently produced on Windows & OSX to manage PostgreSQL 8.4 and above." but perhaps this is not the case for this fork?

As you say, it's not the case for this fork.  This fork was an accident.  The original repo was created and maintained by an outfit called BigSQL.  For a time they had diligently continued maintaining and forward porting pgadmin3 after the pgadmin folks moved on to pgadmin4.  But BigSQL went away I guess (the bigsql.org name doesn't resolve any longer, beyond that I don't know anything,) they deleted their pgadmin3-tls repo and for a time I had the only remaining fork of that repo.  Since then someone with BigSQL forked it back...

Since then I've accepted some conflict free PRs and added one collaborator.  I do not have time to enhance this work, or ensure binaries are building, etc.  I'll update the README to elide the misleading claim of providing binaries.

Should you make the effort to develop pgadmin3-lts I'll accept your PRs and add you as a collaborator as well.  Otherwise you're welcome to fork and do as you will.

**Comment by allentc** [comment]
Re-opening.  Regarding @VVD and the need for a source tarball URL.  I'll look into that.

**Comment by allentc** [comment]
@VVD I've made a dated source only release for the master branch.  The release and its source code archive links will be preserved indefinitely.  Please let me know if it is not sufficient in any way.  I am deliberately not following semantic versioning guidelines; I'd like to avoid implying that there is serious development occurring.

And thanks for your work on FreeBSD.

**Comment by VVD** [comment]
Thanks!
In progress…
Where I can ask or suggest something - in this issue (offtopic :-D)?
Or IRC, or Discord?

**Comment by allentc** [comment]
If you have new issues or questions create a new issue and I'll do what I can.
